name    'alkivi-alkivi_backup'
version '0.0.1'
source 'https://github.com/alkivi-sas/puppet-alkivi_backup'
author 'alkivi'
license 'LGPLv3'
summary 'Controls backup of servers'
description 'Setup backup of servers using duplicity'
project_page 'https://github.com/alkivi-sas/puppet-alkivi_backup'
#dependency 'puppetlabs/stdlib', '>3.x'
#dependency 'puppetlabs/concat', '1.0.0'
#dependency 'puppetlabs/apache', '>0.x'
#dependency 'alkivi/alkivi_base', '>0.x'
dependency torrancew/cron , '>=0.0.3'
